### PR TITLE
A set of powerline-related fixes

### PR DESCRIPTION
**Pull request by ZyX-I**
Most notable is libvterm in dev-libs (maybe it makes sense to remove this package completely, though upstream does not do tests). I hope that presence of libvterm-neovim in dev-libs in *main portage tree* puts an end to the discussion “what category this package should belong to”.

libvterm-neovim mainly exists because you cannot disable stderr warning or debug messages in upstream libvterm and is rather compatible. Also contains some minor fixes AFAIK.

### CODE REVIEW

**Comment by leycec** [comment]
> I hope that presence of libvterm-neovim in dev-libs in main portage tree puts an end to the discussion “what category this package should belong to”.

**\<grumble grumble\>**

You win! I still disagree with that classification, but... I suppose it doesn't particularly matter. We'd better do this the Portage way *before* other ebuilds start depending on `libvterm`.

Thanks for noticing the new `libvterm-neovim` package, bringing this to my attention, *and* fixing this. As always, you're awesome.

**Comment by leycec** [comment]
**O.K.!**

Everything looks great *except* for the commit [installing `bot-ci`'s license](https://github.com/ZyX-I/raiagent/commit/b68edad7a90fad79c62f04b1bd474858f4d97429). Per the Gentoo development guide for the [`src_install()` phase function](https://devmanual.gentoo.org/ebuild-writing/functions/src_install/index.html):

> **Note:** There is no need to `dodoc COPYING`! The license belongs to `${PORTDIR}/licenses`. Sometimes though, you might want to install `COPYING` regardless, if it explains how different licenses are applied to different parts of the application, for example.

Since `bot-ci` only requires the [vanilla MIT license](https://github.com/powerline/bot-ci/blob/master/LICENSE), the latter clause doesn't really apply, implying its `LICENSE` should *not* be installed. If you wouldn't mind removing that commit, I'd be happy to accept everything else without changes.

**Comment by ZyX-I** [comment]
Removed commit that does LICENSE copying.

**Comment by leycec** [comment]
**Superb.** It's in!

**Pull request merged**
